# Generated by Django 4.0.5 on 2022-08-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(auto_created=True)),
                ('enrollment_no', models.CharField(max_length=40, unique=True)),
                ('student_name', models.CharField(max_length=40)),
                ('answer', models.FileField(upload_to='')),
                ('code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConductExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=40, unique=True)),
                ('student_name', models.CharField(max_length=40)),
                ('exam_title', models.CharField(max_length=40)),
                ('paper', models.FileField(upload_to='')),
                ('code', models.CharField(max_length=30)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
            ],
        ),
    ]
