# Generated by Django 4.0.5 on 2022-08-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectexam',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
