# Generated by Django 4.0.5 on 2022-08-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_collectexam_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductexam',
            name='note',
            field=models.TextField(default='Instruction', max_length=500),
        ),
    ]
