# Generated by Django 4.0.5 on 2022-08-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_conductexam_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcontrol',
            name='start_submission',
            field=models.BooleanField(default=False),
        ),
    ]
