# Generated by Django 4.0.5 on 2022-08-01 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_examcontrol_start_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcontrol',
            name='end',
        ),
    ]
