# Generated by Django 4.0.5 on 2022-08-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_examcontrol_end'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examcontrol',
            old_name='start',
            new_name='start_exam',
        ),
    ]
