# Generated by Django 4.0.5 on 2022-07-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_quizresult_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(default='Welcome to St. John!', max_length=100, null=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
