# Generated by Django 4.0.5 on 2022-07-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(blank=True, default='Welcome to St. John', max_length=70, null=True)),
                ('notice_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
