# Generated by Django 4.0.5 on 2022-07-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_addnotice_delete_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnotice',
            name='notice_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
