# Generated by Django 4.0.5 on 2022-07-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('office_at', models.CharField(max_length=100)),
                ('period_of', models.CharField(max_length=100)),
                ('period_to', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('center_id', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
