# Generated by Django 4.0.5 on 2022-07-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcard',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='idcard',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userenrollment',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
