# Generated by Django 4.0.5 on 2022-07-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_admitcard_datetime_certificate_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
