# Generated by Django 4.0.5 on 2022-07-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_admitcard_datetime_alter_certificate_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultHighlightControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
