# Generated by Django 4.0.5 on 2022-08-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_resulthighlightcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='course_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
