# Generated by Django 4.0.5 on 2022-08-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_idcard_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='course_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
