# Generated by Django 4.0.5 on 2022-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_idcard_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
