# Generated by Django 4.0.5 on 2022-08-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_sitedown'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedown',
            name='add_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitedown',
            name='caption',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
