# Generated by Django 4.0.5 on 2022-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField(max_length=250)),
                ('price', models.FloatField()),
                ('semple', models.FileField(upload_to='document_semple')),
                ('thankyou_message', models.TextField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
