# Generated by Django 4.0.5 on 2022-10-16 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_downloaddocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloaddocument',
            old_name='semple',
            new_name='sample',
        ),
    ]
