# Generated by Django 4.0.5 on 2022-10-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_semple_downloaddocument_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloaddocument',
            old_name='discription',
            new_name='description',
        ),
    ]
