# Generated by Django 4.0.5 on 2022-10-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_documentpurchasedstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpurchasedstudent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='documentpurchasedstudent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentpurchasedstudent',
            name='order_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentpurchasedstudent',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
