# Generated by Django 4.0.5 on 2022-10-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_documentpurchasedstudent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpurchasedstudent',
            name='signature',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
