# Generated by Django 4.0.5 on 2022-11-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_documentpurchasedstudent_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='Result_Certificate'),
        ),
    ]
