# Generated by Django 4.0.5 on 2022-12-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='academic_year',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enrollment_no',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specialization',
            field=models.CharField(max_length=40),
        ),
    ]
