# Generated by Django 4.0.5 on 2022-12-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_profile_academic_year_alter_profile_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcard',
            name='address',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='fathers_name',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='issuing_year',
        ),
        migrations.RemoveField(
            model_name='idcard',
            name='validity_year',
        ),
        migrations.AddField(
            model_name='idcard',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards'),
        ),
    ]
