# Generated by Django 4.0.5 on 2022-12-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_idcard_address_remove_idcard_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitcard',
            name='date',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='exam_centre',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='reg_no',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='time',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='title',
        ),
        migrations.AddField(
            model_name='admitcard',
            name='admit_card',
            field=models.FileField(blank=True, upload_to="admitcard_pdf's", verbose_name='Admit Card PDF'),
        ),
        migrations.AlterField(
            model_name='idcard',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='id_cards', verbose_name='Id Card PDF File'),
        ),
    ]
